dummy:
  args: !!python/tuple []
  fullPath: L:\lab_control\quantrolab\lab\instruments\dummy.py
  kwargs: {}
  moduleName: dummy
  state: {}
dummy2:
  fullPath: L:\lab_control\quantrolab\lab\instruments\dummy2.py
  moduleName: dummy2
  state: {}
